### ISSUE TITLE
Incorrectly labeled some images from training set

### ISSUE THREAD

**Issue by albertofernandezvillan** [sensationTI/FLIR_IR_Expansion#1]
Some images from the training set are incorrectly labeled.
Attached you can see the new annotation files correcting the errors

[FLIR_20538.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793572/FLIR_20538.txt)
[FLIR_20773.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793573/FLIR_20773.txt)
[FLIR_20922.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793574/FLIR_20922.txt)
[FLIR_21033.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793575/FLIR_21033.txt)
[FLIR_20354.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793576/FLIR_20354.txt)
[FLIR_20355.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793577/FLIR_20355.txt)
[FLIR_20376.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793578/FLIR_20376.txt)
[FLIR_20377.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793579/FLIR_20377.txt)
[FLIR_20378.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793580/FLIR_20378.txt)

**Comment by sensationTI** [comment]
Thanks for pointing that out, I believe some of the images are from an earlier experiment where some objects are not fully labeled. Will replace them with the correct labeling.

**Comment by sensationTI** [comment]
> Some images from the training set are incorrectly labeled. Attached you can see the new annotation files correcting the errors
> 
> [FLIR_20538.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793572/FLIR_20538.txt) [FLIR_20773.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793573/FLIR_20773.txt) [FLIR_20922.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793574/FLIR_20922.txt) [FLIR_21033.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793575/FLIR_21033.txt) [FLIR_20354.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793576/FLIR_20354.txt) [FLIR_20355.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793577/FLIR_20355.txt) [FLIR_20376.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793578/FLIR_20376.txt) [FLIR_20377.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793579/FLIR_20377.txt) [FLIR_20378.txt](https://github.com/sensationTI/FLIR_IR_Expansion/files/7793580/FLIR_20378.txt)

Thanks for pointing that out, I believe some of the images are from an earlier experiment where some objects are not fully labeled. Will replace them with the correct labeling.
